### ISSUE TITLE
Workflow Design Session: Lesson Plan

### ISSUE THREAD

**Issue by myrandaGoesToSpace** [vanderbilt-data-science/translate-dssg#5]
# Issue: Workflow Design Session - Lesson Plan

## Description

As a team, hold a meeting in which we design exactly how our workflow for the Lesson Plan Draft Tool works. We can use diagrams, descriptions, etc. to write out our ideas. The decisions/designs we make should be preserved in the repo for future reference.

## Acceptance Criteria

- Workflow Design Session held for team members
- Documents from session uploaded to repo

## Deadline

6/14/2024

**Comment by umangchaudhry** [comment]
This took place on 6/6/2024. Please refer to the resources folder for the whiteboard and other information.
