### ISSUE TITLE
Generate API keys

### ISSUE THREAD

**Issue by myrandaGoesToSpace** [vanderbilt-data-science/translate-dssg#7]
# Issue: Generate API Keys for team members

## Description

Umang and Myranda need to generate API keys for the students to use on projects. 

## Details

API keys for the following models:
- OpenAI

## Acceptance Criteria

- API keys assigned one per student and sent to student
- Instructions for using API keys sent to student

## Deadline
6/10/2024

**Comment by umangchaudhry** [comment]
I have created keys for Chloe, Marcus and Matthew. Keys have been sent over slack.
